### ISSUE TITLE
terms to describe type of dataset (provenance)

### ISSUE THREAD

**Issue by andrecastro0o** [ruisdael-observatory/Ruisdael-Data-Catalog#10]
@mschleiss you mentioned yesterday some terms that could be used to describe generally the provenance or type of a dataset, for instance
- surface observation
- remote observation
- model output

I wanted to check with you (@mschleiss) and @fjansson whether you have more or other suggestions for terms that can describe a dataset's provenance. Specially in the model side of things, which I very unfamiliar with, datasets might not only hold model output data, but perhaps "model training data" or similar.   

You input will help help here.

And BTW, this list does not have to be exhaustive or final. We can add and change it, as we go on.

(@fjansson for a bit more of context: here is the link to an example catalog dataset  https://ruisdael-catalog.citg.tudelft.nl/index.php?title=Micro_Rain_Radar_(Metek)_at_Westmaas  it is still a early prototype, I am still working on the schema and form interfaces, but should give you an example:)

**Comment by mschleiss** [comment]
Here are some ideas, courtesy of ChatGPT (edited by me)

### 1. **In-situ Observations**
These datasets are collected directly at the location of interest. Examples include:
- **Surface weather data**: Temperature, humidity, wind speed, and precipitation measurements from ground-based stations.
- **Soundings**: Vertical profiles of temperature, humidity, pressure, and wind collected by instruments carried by weather balloons or radiosondes
- **Aircraft Measurements**: Data collected by instruments onboard research aircrafts.

### 2. **Remote Sensing Observations**
These datasets are collected from a distance, typically using satellites or ground-based remote sensors:
- **Satellite Imagery**: Cloud cover, sea surface temperature, and atmospheric moisture content from satellite observations.
- **Lidar/Radar Measurements**: Vertical profiles or 3D volume scans of aerosols, clouds, and precipitation characteristics from ground-based lids/radar
- **Radiometric Measurements**: Data from passive remote sensing instruments measuring the radiance or reflectance of Earth's surface and atmosphere. Unlike radar/ladar, these sensors do not transmit radiation but only receive it.

### 3. **Model Data**
- **Weather model data**: Outputs from numerical weather models and cloud-resolving models. Analysis and forecasts.
- **Climate models data**: The same as above but for global scales and longer time periods (climate scale)
- **Reanalysis Data**: Reanalysis datasets are created by assimilating historical observational data into models to provide a comprehensive and consistent dataset. 

### 5. **Derived/Processed Data**
- **Composite Datasets**: Data products that combine multiple data types and sources, such as blended satellite and in-situ temperature records, or higher level products.

### 6. **Geospatial Data**
Datasets that include spatial information about the Earth's surface, sub-surface and atmosphere. Examples include:
- **Digital Elevation Models (DEM)**: Information on terrain and surface features.
- **Land Cover and Land Use Data**: Data describing the type and extent of vegetation, urban areas, water bodies, etc.

### 7. **Historical and Paleoclimate Data**
Datasets that provide information about past climates using proxy data or historical records. Examples include:
- **Ice Core Records**: Information on past atmospheric composition and temperature.
- **Tree Ring Data**: Data providing insights into historical climate variability.

**Comment by andrecastro0o** [comment]
thank you @mschleiss and @chatgpt :laughing:  looks like quite a complete list and at a level of granularity that seems to be at a sweet-spot, detailed enough but not over complex. 
I will let you know when it is implemented in the catalog!

**Comment by mschleiss** [comment]
By the way,  I am not a big fan of the term "data provenance" and would suggest alternative names such as "data type" or "source"

**Comment by andrecastro0o** [comment]
I have included the top 7 types as possible values of a Dataset type.

If wished the sub-types can be included later, but I think this is enough for now

![Screenshot 2024-07-10 at 14-55-10 Edit Dataset Micro Rain Radar (Metek) at Westmaas - Ruisdael Observatory Data Catalog](https://github.com/ruisdael-observatory/Ruisdael-Data-Catalog/assets/1690557/504250ae-df3d-4236-8418-965e180dccd8)
