### ISSUE TITLE
Request for a new account

### ISSUE THREAD

**Issue by msourzac** [ruisdael-observatory/Ruisdael-Data-Catalog#31]
### Name

Mahaut Sourzac

### Email address

m.sourzac@tudelft.nl

### Organization

TU Delft

### Role

Technician

**Comment by mschleiss** [comment]
Unfortunately, I do not have the permissions to create accounts. @andrecastro0o When you have time, could you upgrade my account please?

**Comment by andrecastro0o** [comment]
> Unfortunately, I do not have the permissions to create accounts. @andrecastro0o When you have time, could you upgrade my account please?

@mschleiss thank you for jumping on this request.

I have increased your user rights.

In any case I will close the issue as @msourzac already has an account
